### ISSUE TITLE
Missing use cases

### ISSUE THREAD

**Issue by indragiek** [CMPUT301W15T09/Team9Project#11]
We're missing use cases that reference the following user stories:
- [x] US01.06.01
- [x] US04.04.01
- [x] US04.08.01
- [x] US07.03.01
- [x] US07.04.01
- [x] US08.06.01
- [x] US08.09.01

**Comment by mrthegreensky** [comment]
I'll finish off 4.04 and 4.08 rn

**Comment by mrthegreensky** [comment]
Gonna do 8.06 now

**Comment by nmrcarroll** [comment]
US07.03.01 and US07.04.01 have been added as refferences to "5.4 Approve or Disapprove an Expense Claim"

**Comment by stebenc** [comment]
working on 8.09

**Comment by stebenc** [comment]
the table of contents needs to be updated once everything is added

**Comment by indragiek** [comment]
Will do
