### ISSUE TITLE
Storing Expense Claims on ElasticSearch

### ISSUE THREAD

**Issue by indragiek** [CMPUT301W15T09/Team9Project#29]
/cc @jimmyho899 

I've been thinking about how to store expense claims on ElasticSearch, and it seems like the easiest way would be to store each `ExpenseClaim` object as a document on ElasticSearch with a `claimaintID` and `approverID` fields that contain the user ID's for the users that created and (optionally) approved the claim. 

In order to find expense claims that were created by a particular user, we can use ElasticSearch's [Request Body Search](http://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-request-body.html) or [URI Search](http://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-uri-request.html) APIs.

Here's a preliminary breakdown of the tasks involved:
- [x] Add `claimantID` and `approverID` fields to `ExpenseClaim`
- [x] Make `ExpenseClaim` implement `ElasticSearchDocument`
- [x] Add search capabilities to `ElasticSearchAPIClient`
- [x] Create a shared singleton "manager" class that contains a reference to both the shared `ListModel<ExpenseClaim>` instance and an instance of `ElasticSearchAPIClient` for performing requests.
  - [x] Implement a network status listener
  - [x] Implement a queue of pending API calls with support for retry with exponential backoff for when the device cannot reach the network
  - [ ] ~~Implement some kind of serialization mechanism such that if the user quits the application while there are pending API calls, the requests are serialized to disk and restarted when the app opens the next time. Have to be careful when doing this while new data is being loaded in from the server.~~
- [ ] Fix persistence so that the data is saved even without the user pressing the back button (@bjw1 brought this up)

**Comment by jph899** [comment]
So are we going to randomly generate ids for the user? one for approver and one for claimant? Then everytime we add a claim we will ad those ids into the expense claim?

**Comment by indragiek** [comment]
Yeah they would be randomly generated identifiers. When the expense claim is created the `claimantID` would be assigned and the `approverID` would be assigned when it is approved.

**Comment by indragiek** [comment]
Last task is being tracked in #42.
