### ISSUE TITLE
Expense Items / Overall / Listing / Receipts

### ISSUE THREAD

**Issue by williums** [CMPUT301W15T09/Team9Project#3]
Jimmy Ho and Brandon Williams

Expense Items / Overall
- [x] **US04.01.01**
  As a claimant, I want to make one or more expense items for an expense claim, each of which has a date the expense was incurred, a category, a textual description, amount spent, and unit of currency.
- [x] **US04.02.01**
  As a claimant, I want the category for an expense item to be one of air fare, ground transport, vehicle rental, private automobile, fuel, parking, registration, accommodation, meal, or supplies.
- [x] **US04.03.01**
  As a claimant, I want the currency for an expense amount to be one of CAD, USD, EUR, GBP, CHF, JPY, or CNY.
- [x] **US04.04.01**
  As a claimant, I want to manually flag an expense item with an incompleteness indicator, even if all item fields have values, so that I am reminded that the item needs further editing.
- [x] **US04.05.01**
  As a claimant, I want to view an expense item and its details.
- [x] **US04.06.01**
  As a claimant, I want to edit an expense item while changes are allowed.
- [x] **US04.07.01**
  As a claimant, I want to delete an expense item while changes are allowed.
- [x] **US04.08.01**
  As a claimant, I want the entry of an expense item to have minimal required navigation in the user interface.

Expense Items / Listing
- [x] **US05.01.01**
  As a claimant, I want to list all the expense items for a claim, in order of entry, showing for each expense item: the date the expense was incurred, the category, the textual description, amount spent, unit of currency, whether there is a photographic receipt, and incompleteness indicator.

Expense Items / Receipts
- [x] **US06.01.01**
  As a claimant, I want to optionally take a single photograph of a receipt and attach the photograph to an editable expense item, so that there is supporting documentation for the expense item in case the physical receipt is lost.
- [x] **US06.02.01**
  As a claimant, I want to view any attached photographic receipt for an expense item.
- [x] **US06.03.01**
  As a claimant, I want to delete any attached photographic receipt on an editable expense item, so that unclear images can be re-taken.
- [x] **US06.04.01**
  As a sysadmin, I want each receipt image file to be under 65536 bytes in size.

**Comment by mrthegreensky** [comment]
Brandon and Jimmy will be working on this
