### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by williums** [CMPUT301W15T09/Team9Project#34]
- [x] Attach geolocation to destinations
- [x] Claims should have color codes to indicate distance of it's first destination geolocation to the home geolocation
- [x] Optionally attach geolocation to expense items
- [x] Geolocation indicator on expense item listings
- [x] Set home geolocation
- [x] Specify geolocation by map
- [x] Specify geolocation by GPS
- [x] View geolocations on a map

**Comment by indragiek** [comment]
Remember to update the Reuse Statement page (https://github.com/CMPUT301W15T09/Team9Project/wiki/Reuse-Statement) with the libraries you added for implementing this stuff.

**Comment by indragiek** [comment]
Places API won't work without a network connection so I'm working on a fallback that allows for entering locations using lat/long coordinates.

**Comment by indragiek** [comment]
Any class that is already using `PlacePickerParentActivity` will get this functionality for free once it is implemented.
