### ISSUE TITLE
Categories and currencies

### ISSUE THREAD

**Issue by williums** [CMPUT301W15T09/Team9Project#38]
I went over the project problem description and I realized that we didn't edit the app to include the new types of currencies ( CHF, JPY, CNY ), and also the categories should be (air fare, ground transport, vehicle rental, private automobile, fuel, parking, registration, accommodation, meal, or supplies). I was also wondering if that bug with joda money was fixed yet?

**Comment by indragiek** [comment]
What was the Joda Money bug? Adding new currencies and categories should just be a matter of editing the XML files that those lists are loaded from.

**Comment by williums** [comment]
There was a bug where if we entered currency amounts that weren't a multiple of $0.25 it would crash

**Comment by indragiek** [comment]
Was the bug in our code or was the crash inside Joda Money?

**Comment by williums** [comment]
I can't pull it off the top of my head and I'm at work so I can't check, but I think joda complained about decimal places. Everything that wasn't a multiple of 0.25 came up as a really long float value or something, Andrew saw it too

**Comment by indragiek** [comment]
I see, let's keep this issue open and look into it at some point then.

**Comment by mrthegreensky** [comment]
It was with Joda money I believe

**Comment by mrthegreensky** [comment]
Actually, I think it might just be us. The error is:
04-04 01:42:49.102: E/AndroidRuntime(11319): java.lang.ArithmeticException: Scale of amount 0.949999988079071 is greater than the scale of the currency CAD

It's found when we parse the number. I entered 0.95 for the value. It only works for values of x.25, x.50, x.75, and x.00
