### ISSUE TITLE
Expense Claims / Statuses

### ISSUE THREAD

**Issue by stebenc** [CMPUT301W15T09/Team9Project#4]
- [x] **US07.01.01**
  As a claimant, I want to submit an expense claim for approval, denoting the claim status as submitted, with no further changes allowed by me to the claim information (except the tags).
- [x] **US07.02.01**
  As a claimant, I want a visual warning when trying to submit an expense claim when there are fields with missing values or there are any incompleteness indicators on the expense items.
- [x] **US07.03.01**
  As a claimant, I want a submitted expense claim that was not approved to be denoted by a claim status of returned, with further changes allowed by me to the claim information.
- [x] **US07.04.01**
  As a claimant, I want a submitted expense claim that was approved to be denoted by a claim status of approved, with no further changes allowed by me to the claim information (except the tags).
- [x] **US07.05.01**
  As a claimant, I want to see the name of the approver and any comment(s) from the approver on a returned or approved claim.

**Comment by nmrcarroll** [comment]
I'll work on this one
