### ISSUE TITLE
Fix approver/comments UI

### ISSUE THREAD

**Issue by indragiek** [CMPUT301W15T09/Team9Project#47]
The UI for approver and approver comments is not well integrated into the rest of the detail screen UI right now. Also, having a "User" field is redundant because the user's name should be displayed in the name feel at the top, since expense claims no longer have names of their own.

**Comment by stebenc** [comment]
any suggestions? i was thinking there be a "view comments" button in place of the current comments edittext that takes the user/approver to a new layout that only contains a list of comments. then the approver can add a comment from the top right drop down menu

**Comment by indragiek** [comment]
That sounds good. An alternate way to do it would be to embed the list of comments directly inside the detail activity list. See `ExpenseClaimDetailController` for how to add a section to that list (just like tags, destinations, expense items, etc.). Then you could add a menu item to the detail activity to add a comment.

**Comment by stebenc** [comment]
since the comments have no restrictions and the approver can leave many, wouldn't that stretch the details screen if there are a lot of comments/multi line comments?

**Comment by indragiek** [comment]
Yeah, fair enough. Maybe a separate screen is better then.

**Comment by indragiek** [comment]
Should mention: the comment "cells" should have both the name of the approver and the comment text in them, as there could be more than one person reviewing the claim. The cell should also indicate whether the approver rejected or accepted the claim.

**Comment by mrthegreensky** [comment]
Won't there be a case where a claim is both rejected and accepted? Or should we make it so that once it's accepted, it's just accepted?

**Comment by mrthegreensky** [comment]
Oh wait, nevermind, found answer on the forums :)

**Comment by stebenc** [comment]
Each comment should kind of look like an expense claim, so it has the approver name, date, status, and then the comment part itself. Then it is simply integrated into the details layout and not a separate one for simplicity sake. 
i was indecisive on how to add a comment - through an activity or similar to how a destination is made, so things are messy

**Comment by indragiek** [comment]
An `AlertDialog` should suffice for adding a comment, since it's only a single field.
