### ISSUE TITLE
Demo presentation

### ISSUE THREAD

**Issue by indragiek** [CMPUT301W15T09/Team9Project#53]
From the part 5 requirements:

> Provide an engaging live demo. Do not play your demo video with audio. If it has audio, talk over it. Make sure your presentation is LIVE.

**Comment by stebenc** [comment]
i'm free on tuesday after the project is due i guess. i dunno how alive i will be though
also on wednesday after 12:30 probably

perhaps if any one has any series of vacation photos we can have a slideshow mixed in with over the shoulder recordings of the app being used on an actual android device. it'll be like faking a real trip and we can add the items and destinations that show from the pictures.
then we can "talk" to the screen or video i.e "as you can see, our users can add multiple items to their claims. (they close the app) hey [person on vacation], don't forget to include the dinner that you had! (" (reopens app and adds it in) and we will have recorded a thumbs up from the person in the video
wow, how engaging!

**Comment by indragiek** [comment]
@PiratePlex That's a pretty cool idea, I like that.

Unfortunately, myself (and probably @mrthegreensky) will be MIA for this part, we have another project to finish this week :/

**Comment by PiratePlex** [comment]
I really don't want to do some boring screen recording of the emulator. Does anyone have any resources and time to make something more interesting? i have practically all day on wednesday free. they suggested one rehearsal so i dont know if theres a period where we're all free considering its still crunch time for some assgnments

**Comment by stebenc** [comment]
a live demo on the emulator sounds even worse so i think that will be out of the question for sure.

this seems ok i guess:
-    If you need to project your phones or tablets bring a laptop with webcam software so you may project a webcam video of your phone in action. Otherwise, enable screen sharing so you can project (I cannot provide any tech support for this).

**Comment by mrthegreensky** [comment]
if they have hdmi port i have a chromecast
