### ISSUE TITLE
Editting destination geolocations

### ISSUE THREAD

**Issue by williums** [CMPUT301W15T09/Team9Project#64]
So as of the most latest commit in the branch destination_geolocation, we can create new destinations and set a geolocation, but when we try and re-open the geolocation the app will crash with a NullPointerException coming from getLatitude at line 473 of ExpenseClaimDetailActivity. We used logcat to check the indexes and order of the destinations list and they all seem to be matching up correctly. Oddly enough, the first destination can have the geolocation set and edited without a problem, but everything else will crash. I'm thinking it's since claims.getDestinations returns an unmodifiableList but I'm not entirely sure.

**Comment by indragiek** [comment]
The unmodifiable list shouldn't be an issue unless you're trying to change the list, which you aren't in this case. I'll take a look at this tomorrow if you haven't sorted it out by then.

**Comment by mrthegreensky** [comment]
Agreed. What kind of error does it give?

**Comment by jph899** [comment]
It gives a null pointer but when we tested yesterday the list of destinations were correct and the index was also correct. For some reason the getLatitude and getLongitude would cause it to crash

**Comment by indragiek** [comment]
Going to close this issue since it won't be relevant to what @mrthegreensky is working on now.
