### ISSUE TITLE
Odd Crash

### ISSUE THREAD

**Issue by williums** [CMPUT301W15T09/Team9Project#73]
I encountered an odd screen of expense claims after the app crashed on multiple occasions... I cleared the data and uninstalled the app a few times but when I go in to try and set the home location for the first time, the app sometimes crashes while I'm in Google Places and sometimes crashes when I return from it. One time I made it all the way to adding a claim and then it all crashes. Oddly enough, when I restart the app again I get the same screen of expense claims
![screenshot_2015-04-06-18-45-53](https://cloud.githubusercontent.com/assets/10455402/7015223/a529cc50-dc8d-11e4-8d84-00febc4054ff.png)

**Comment by indragiek** [comment]
Do you have exception traces for these crashes?

**Comment by williums** [comment]
Some of them have Indragie as the user, some have Nic, and other random usernames

**Comment by williums** [comment]
It's all still in my logcat, how do you want me to show it

**Comment by indragiek** [comment]
@bjw1 Yeah, I've seen that before. Somehow it's not filtering the claims to the correct user. But it shouldn't crash. Paste the logs here.

**Comment by indragiek** [comment]
@bjw1 Or use a gist (https://gist.github.com)

**Comment by williums** [comment]
https://gist.github.com/bjw1/7e6e49b9045162406c95

**Comment by bjw1** [comment]
ok no thats not it wait

**Comment by williums** [comment]
I cleared data, then opened the app and it took me to the user settings activity where I tried to set a home location. It crashed upon loading Google Places. 
I pressed back until I got to the app, and I went past the User Settings activity and into the ExpenseClaimsListActivity. 
I went back to User Settings from the action bar and set my location again, and this time it worked. I tried to make a new claim but it crashed after getting to that new activity.
I swiped the app away in task manager and reopened it, and it prompted me for User and Home Location again. Crashed the same way as it did the first time

**Comment by williums** [comment]
![screenshot_2015-04-06-19-02-29](https://cloud.githubusercontent.com/assets/10455402/7015353/9f22dc78-dc8f-11e4-9280-4e87c0f7d61b.png)
This is the screen I see upon opening it again, I just closed the app and reopened it

**Comment by indragiek** [comment]
@bjw1 Which branch are you on? From the exception traces, all of the crashes are due to the `ListModel` used for filtering not being able to open the file it uses to store them. 

@mrthegreensky Maybe we should add a parameter to `ListModel` that tells it not to save stuff on disk? Because we don't really need it to save the filtered list on disk.

**Comment by williums** [comment]
I'm on geolocations_expenseitems but i only made changes to ExpenseItemAddActivity so far. I was gonna check the UI but I never even got there

**Comment by mrthegreensky** [comment]
I don't think it ever saves it on the disk. It should just persist until the applications is closed

**Comment by williums** [comment]
It's not on disk since I uninstalled the app entirely. Also I've never made those claims before

**Comment by williums** [comment]
The users vary but some are nic and indragie, and also I've never made destinations to Mexico or Hawaii

**Comment by indragiek** [comment]
@bjw1 Can you merge in the `geolocation` branch? I'm pretty sure I fixed this already but you don't have the commit. Showing other people's claims is a known issue, I will be looking into that. Shouldn't crash though.

**Comment by indragiek** [comment]
@bjw1 Make sure you trash the app, clean, refresh before trying to run it again after merging.

**Comment by williums** [comment]
Ok this is a new one....
![screenshot_2015-04-06-19-36-34](https://cloud.githubusercontent.com/assets/10455402/7015659/4d5c62ba-dc94-11e4-83f2-eea8d8355bdf.png)

**Comment by williums** [comment]
I got past setting a home location, but this time it crashed when I tried to make a claim

**Comment by indragiek** [comment]
@bjw1 I think that's @jimmyho899 testing out colors

**Comment by indragiek** [comment]
@bjw1 New crash log?

**Comment by williums** [comment]
https://gist.github.com/bjw1/e2e76778a1c5c298cc4b

**Comment by indragiek** [comment]
@bjw1 This is the same crash as before, something to do with filtering.

@mrthegreensky Can you look into this when you're done with what you're doing right now?

**Comment by jph899** [comment]
I do not crash when I add a claim or item on my emulator. I am also on the geolocation branch.

**Comment by williums** [comment]
I can make claims without crashing if I don't set a Home Location

**Comment by mrthegreensky** [comment]
Yes sir

**Comment by indragiek** [comment]
Makes sure you guys pull the latest master and this should be fixed now, most of that code has been rewritten.
