### ISSUE TITLE
Errors when adding locations to an expense item

### ISSUE THREAD

**Issue by williums** [CMPUT301W15T09/Team9Project#81]
https://gist.github.com/bjw1/84a1d4518a44c7fbf8d9
I don't really understand why this one is happening. Doesn't happen every time either.

**Comment by indragiek** [comment]
This is a problem with Eclipse. If you Clean your project it'll work fine.

**Comment by williums** [comment]
I'm still getting this problem, and not just in that activity. When I go edit the User Home Location, it happens too with the same error messages

**Comment by indragiek** [comment]
If that's the case I think you're looking at the wrong exception trace, because if it was the exception you pasted then the app wouldn't even start.

**Comment by williums** [comment]
I'm not sure, I'm still on my branch but it keeps happening to me on multiple occasions and it is that stack trace

**Comment by williums** [comment]
On another note, every time I try to clean my project I get errors. Does this have anything to do with it?
![untitled](https://cloud.githubusercontent.com/assets/10455402/7018210/cab883c2-dcbe-11e4-8442-627e59349f79.png)

**Comment by indragiek** [comment]
@bjw1 It might. I've seen that before, it is fixed by removing the google play project from your workspace and adding it back (via File > Import) and cleaning the project again.

**Comment by williums** [comment]
@indragiek I actually did that just a few minutes ago and it still happens. I removed all 3 of the projects and re-added them, then tried to clean.

**Comment by indragiek** [comment]
I'm not sure :/ You've tried restarting Eclipse right?

**Comment by williums** [comment]
Yeah, the only thing I haven't done is restart my pc, which I'm about to do now.

**Comment by williums** [comment]
Back from rebooting my pc. I can clean the project now without errors but I still get the same problem when adding a location to an expense item. Same error message too, it happens right before google places loads up the map. I trashed the app and reinstalled it onto my phone

**Comment by indragiek** [comment]
Try merging master into your branch, I fixed a bunch of stuff there. Maybe it will help.

**Comment by indragiek** [comment]
Did this work after merging into master?
